### ISSUE TITLE
Field*Attribute classes should be marked as [AttributeUsage(AttributeTargets.Field | AttributeTargets.Property)]

### ISSUE THREAD

**Issue by xumix** [MarcosMeli/FileHelpers#221] opened 2017-01-24 15:02 UTC
subj, since I cannot use them on properties, and all my classes are property-based

**Comment by ciarancolgan** [comment] 2017-03-13 12:00
Careful if you are making this change yourself as the code in ReflectionHelper.cs is using ".GetFields" not ".GetProperties" so it wont pick up anything. I tried it myself and backed out once i realised the implications :)
It's easy enough to just map your model with Fields in it to one with Properties after the fact if you're ok with that? Use AutoMapper to make life easier.

**Comment by xumix** [comment] 2017-03-13 12:20
@ciarancolgan I just decided to dump FileHelpers and use CsvHelper, I really do not want to multiply entities in my project just to have props

**Comment by mcavigelli** [comment] 2017-05-11 19:19
This seems to be a duplicate of #67.
@ciarancolgan thank you for your explanations.

**Closed by mcavigelli** 2017-05-11 19:19 UTC
