### ISSUE TITLE
DelimitedClassBuilder BadUsageException

### ISSUE THREAD

**Issue by AntonioGa** [MarcosMeli/FileHelpers#307] opened 2018-09-13 10:44 UTC
```
public async Task EsportazioneArticolo(Setup_Profilo_Azienda spa, IEnumerable<Export_Articolo> eas)
        {
            var cb = EsportazioneCreaDefinizione<Export_Articolo>(spa);
            var engine = new DelimitedFileEngine(cb.CreateRecordClass());
            engine.WriteFile($"{spa.OutputFolder}\\ARTICOLI.txt", eas);
        }
        private static DelimitedClassBuilder EsportazioneCreaDefinizione<T>(Setup_Profilo_Azienda spa)
        {
            var description = typeof(T).GetCustomAttribute<DescriptionAttribute>().Description;
            var spat = spa.Tracciati.Single(m => m.Nome == description);
            var campi = spat.Campi.Where(m => m.Order.HasValue).OrderBy(m => m.Order).ThenBy(m => m.Nome).ToList();
            var cb = new DelimitedClassBuilder(typeof(T).Name, ";");
            campi.ForEach(c =>
            {
                var pi = typeof(T).GetProperty(c.Nome);
                var dcb = cb.AddField(c.Nome, pi.PropertyType);
            });
            return cb;
        }
```
engine.WriteFile($"{spa.OutputFolder}\\ARTICOLI.txt", eas); -> FileHelpers.BadUsageException: 'This engine works with record of type Export_Articolo and you use records of type Export_Articolo'

**Comment by mcavigelli** [comment] 2018-09-28 20:01
Hello Antonio

Thank you for using FileHelpers. By looking at your code I cannot find the reason.

The somehow weird looking message is caused by _new DelimitedClassBuilder(typeof(T).Name_ and the parameter _IEnumerable<Export_Articolo> eas_. Changing the name of the dynamically generated class will clarify the exception message, but will probably not fix the problem).

To reproduce your problem I must be able to compile and run it. I cannot compile your snippet.
You create the dynamic class with _Setup_Profilo_Azienda_ and export objects of type _Export_Articolo_,
is that correct?

Matthias

**Comment by mcavigelli** [comment] 2018-09-28 20:16
I have just noticed that this is a duplicate of #293.
It seems that we already have sample code to reproduce the issue.

**Closed by mcavigelli** 2018-09-28 20:16 UTC
